version: '3.4'

services:
  merchants-web:
    image: ${DOCKER_REGISTRY-}merchantsweb
    build:
      context: .
      dockerfile: Merchants.Web/Dockerfile
    ports:
      - "7500:80"
      - "7501:433"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7501
      - ConnectionStrings__MerchantsAppConnection=Server=merchants-db;Database=Merchants;User=sa;Password=Merchant_App_123;      
    depends_on:
      - merchants-db
  merchants-db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Merchant_App_123"
      ACCEPT_EULA: "Y"
    ports:
      - "7000:1433"
